openapi: 3.0.0
info:
  title: My API
  version: 2024-03-01
servers:
  - url: https://api.example.com
    description: Production server
tags:
  - name: users
    description: Users related operations
paths: {}
